name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker -q

      - name: Build be-tts-en image
        run: docker build . --build-arg ENV=prod --file Dockerfile --tag gcr.io/practical-robot-304901/cheaptts-tts-en:${{steps.vars.outputs.tag}}

      - name: Push be-tts-en image
        run: |-
          docker push gcr.io/practical-robot-304901/cheaptts-tts-en:${{steps.vars.outputs.tag}}
